### ISSUE TITLE
iPython kernel crashes and restarts when simulating FMU including "terminate" command

### ISSUE THREAD

**Issue by sitadrost** [modelon-community/PyFMI#157]
Using OpenModelica 1.19.2, I've built an electrical circuit model of a periodic system with period `Tc`. To make sure that my model simulates an integer number of periods, I've included the following commands:
```
when time >= duration then
    terminate("Completed 10 cycles");
  end when;
```
where `duration = 10*Tc` (smaller than `StopTime`).

This works fine in OpenModelica, but when I export an FMU of this model and import it into Python using PyFMI, it will only simulate when I set `final_time` to some value <= `duration`. When I don't set `final_time`, or set it to some value larger than `duration`, my iPython kernel crashes and restarts:
```
Fatal Python error: Segmentation fault


Main thread:
Current thread 0x00007f5e3eb23740 (most recent call first):
  File "/home/sita/miniconda3/envs/modelica/lib/python3.10/site-packages/pyfmi/fmi_algorithm_drivers.py", line 718 in solve
  File "/tmp/ipykernel_11055/918709914.py", line 1 in <cell line: 1>


Restarting kernel...
```
I can of course prevent this from happening by making sure that `final_time` in Python never exceeds `duration`, which shouldn't be too hard, but now I'm curious why I'm getting this error. Is `final_time` trying to overrule this `terminate` command, or is something else happening?

Possibly relevant details:
* Ubuntu 20.04
* OpenModelica 1.19.2
* PyFMI version 2.9.7 (conda-forge)
* Spyder version: 5.3.2  (conda)
* Python version: 3.10.5 64-bit
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Linux 5.15.0-48-generic

**Comment by modelonrobinandersson** [comment]
@sitadrost have you looked if this is happening due to the FMU itself and not PyFMI? I tried using terminate in a simple model and I didn't encounter an issue:  
`
model MyModel  
  Real x;  
algorithm  
  when time > 1.2 then  
    terminate("Terminated.");  
  end when;  
equation  
  der(x) = -x;  
end MyModel;  
`
If I try for example simulating this to `t=1.5`:  
`
In [9]: fmu.simulate(0, 1.5)  
Terminating simulation at t = 1.200000 after signal from handle_event.  
Final Run Statistics: ---  
...
Simulation interval    : 0.0 - 1.2 seconds.  
Elapsed simulation time: 0.032829200000008996 seconds.  
`

**Comment by sitadrost** [comment]
Thanks a lot for looking into this @modelonrobinandersson ! I copied your simple model into OpenModelica, exported an FMU, and loaded this into Python using PyFMI. When running it as `fmu.simulate(0, 1.5)` I get the exact same error as with my own FMU:
```
Fatal Python error: Segmentation fault


Main thread:
Current thread 0x00007fcb4e106740 (most recent call first):
  File "/home/sita/miniconda3/envs/modelica/lib/python3.10/site-packages/pyfmi/fmi_algorithm_drivers.py", line 718 in solve
  File "/tmp/ipykernel_9543/1831878345.py", line 1 in <cell line: 1>


Restarting kernel...
```
Not sure whether it's the FMU or PyFMI (or something else entirely) that's causing this error though. Did you use OpenModelica for your test, or some other Modelica software (e.g. Dymola, JModelica)?

**Comment by modelonrobinandersson** [comment]
@sitadrost Correct, I used _Modelon Impact_. I would propose that you see if OpenModelica has an issue with FMUs that invoke `terminate`. I was also suspecting if your PyFMI installation is the issue but I cannot think of any reason why it would make IPython crash, especially since it crashed for you during the simulation.

**Comment by sitadrost** [comment]
Thanks, I'll have a look at OpenModelica
