### ISSUE TITLE
Memory leakage for PyFMI

### ISSUE THREAD

**Issue by lambtt** [modelon-community/PyFMI#160]
Hi, I am using PyFMI to do optimization-based control for my model.

Therefore, lots of simulations in the loop will be run.

I found that with more and more simulations, my memory will increase to a very big number, like 100% for a 16 GB computer.

I did a simple test and found a memory leakage every time I ran the method "simulate".

![Snipaste_2022-12-19_17-34-44](https://user-images.githubusercontent.com/91109801/208548410-c4915016-efeb-4828-becf-3970348d6a44.png)

The memory increased to 6 MB / per simulation.

I also tried to delete the reset and initialization methods, but it still did not work.

I wonder if there is any method to release the memory after the simulation. So I could only save the states for the next simulation and don't need to worry about the memory issue.

I appreciate any hints. Thanks!

**Comment by PeterMeisrimelModelon** [comment]
Is it possible to share a complete example that reproduces the issue. From your code snippet it is not clear what "self" is and how this actually interacts with PyFMI.

**Comment by modelonrobinandersson** [comment]
@lambtt have you checked if it is not the FMU itself that is leaking memory?

**Comment by PeterMeisrimelModelon** [comment]
I am not sure I understand fully understand the leakage part of the issue.

1. You want to run a model **n** (large) times. Each time saving a state. These are to be used later on separately.
2. If you run out of memory here, this means there is a limitation on how many states you can save at once,

I wouldn't call this a memory leak, since you are specifically storing the states. A way around this would be to serialize the states via **model.serialize_fmu_state(<fmu_state>)** and then e.g., write them to a file and load them again when needed, de-serializing them via **model.deserialize_fmu_state(<serialized_fmu_state>)**.

This may still cause issues for very large **n**, in case the generated FMU states still exists somewhere inside the FMU and occupy memory (not sure if this would be an issue of PyFMI or the FMU). A possible remedy of this could be to subdivide your loop over **n** into 2 loops: for j in range(m): .... for i in range(n//m): .... and make loading the FMU part of the outer loop.

**Comment by modelonrobinandersson** [comment]
@lambtt Just FYI, I'd like to mention that the actual implementation of get/set state is in the tool that you have used to generate the FMU. The PyFMI functions get/set state act more or less as wrapper code to invoke necessary FMI functions that ultimately invoke functions implemented by the tool vendor.
This implies that if you have issues such as memory leaks when invoking get/set state, there _could_ be an issue in the implementation on the tool side.

**Comment by modelonrobinandersson** [comment]
@lambtt when you say "_the JModelica way_", do you mean that you load the FMU generated with Dymola using PyFMI, then with Python you (again via PyFMI) you get/set state followed by a simulation and plotting the results above? The reason why I am asking is because PyFMI and JModelica are two different things and I want to make sure I understand your situation correctly.

**Comment by PeterMeisrimelModelon** [comment]
> > I am not sure I understand fully understand the leakage part of the issue.
> > 
> > 1. You want to run a model **n** (large) times. Each time saving a state. These are to be used later on separately.
> > 2. If you run out of memory here, this means there is a limitation on how many states you can save at once,
> > 
> > I wouldn't call this a memory leak, since you are specifically storing the states. A way around this would be to serialize the states via **model.serialize_fmu_state(<fmu_state>)** and then e.g., write them to a file and load them again when needed, de-serializing them via **model.deserialize_fmu_state(<serialized_fmu_state>)**.
> > This may still cause issues for very large **n**, in case the generated FMU states still exists somewhere inside the FMU and occupy memory (not sure if this would be an issue of PyFMI or the FMU). A possible remedy of this could be to subdivide your loop over **n** into 2 loops: for j in range(m): .... for i in range(n//m): .... and make loading the FMU part of the outer loop.
> 
> Thanks a lot, @PeterMeisrimelModelon , I will try it as you suggested to see if it works! BTW, my model has 81 states, and after every simulation, the states would be updated and the old states will be deleted (use "del states"). However, it still introduced a leakage. I wonder it's not because my states get bigger and bigger with the simulation continued.

I had another look at this and did some testing.

The correct way to delete saved states is via

```
fmu.free_fmu_state(state)
del(state) # probably only optional
```

Explanation:
- A FMU save-state is internal to the FMU.
- Calling fmu.get_fmu_state() queries the FMU to generate an internal save-state, returned in the form of a pointer to PyFMI. PyMFI packages this along with some other data and returns this as a Python object.
- Calling fmu.free_fmu_state(state) queries the FMU to free the memory associated with the internal state it created.

If memory leaks persist, these may be due to the FMU not correctly cleaning up its own internal states.

**Comment by PeterMeisrimelModelon** [comment]
> Yes, this is what I was talking about! The FMU was generated from Dymola. I use two methods to set or get state for this FMU.
> 
> --Method 1: (Dymola way) ----Get state: fmu_get_state ----Set state: fmu_set_state
> 
> --Method 2: (JModelica way: The reason that I call this method JModelica way is because this method would work well with the FMU generated from JModelica) states_names = fmu.get_states_list() states = {} ----Get state: for name in states_names: states[name] = fmu.get(name) ----Set state: for name in states.keys(): fmu.set(name, states[name])
> 
> For a FMU generated by Dymola, Method 1 would return results which is as same as Dymola software's results. Method 2 would return unreasonable results.

Method 1 is generally the recommended way to restore states. Method 2 may work in some cases, but there is no guarantee.

**Comment by PeterMeisrimelModelon** [comment]
Happy to hear that it solved your problems. 

Found this mostly by looking through the code, seeing how it interacts with the PyFMI savestate objects generated:

https://github.com/modelon-community/PyFMI/blob/d4472011f1529e9acafa3db88393f2658414e8e5/src/pyfmi/fmi.pyx#L128

Having worked with savestates on the FMU side also helped :)
