### ISSUE TITLE
completed_integrator_step returns a tuple instead of a boolean

### ISSUE THREAD

**Issue by marcelotomim** [modelon-community/PyFMI#174]
Dear All,

I am simulating an FMU based on the example [fmi_bouncing_ball_native.py](https://github.com/modelon-community/PyFMI/blob/master/src/pyfmi/examples/fmi_bouncing_ball_native.py). 

In my implementation, however, the method `completed_integrator_step()` of an `FMUModelME2` instance, returns a tuple with two elements ([False, False]) instead of a boolean. It does not seem to be correct according to the method help text shown below:

>Help on built-in function completed_integrator_step:
>
>completed_integrator_step(...) method of pyfmi.fmi.FMUModelME2 instance
>    This method must be called by the environment after every completed step
>    of the integrator. If the return is True, then the environment must call
>    event_update() otherwise, no action is needed.
>    
>    Returns::
>    
>        True -> Call event_update().
>        False -> Do nothing.
>    
>    Calls the low-level FMI function: fmi2CompletedIntegratorStep.

Could anyone please help me on this?
Thanks in advance for the attention.

**Comment by modelonrobinandersson** [comment]
Hi @marcelotomim thank you for raising this.
It appears that the docstring for `FMUModelME2` is incorrect. The behavior in the docstring explains the behavior for the old behavior used in `FMUModelME1`. The correct and expected behavior for `FMUModelME2` is a tuple where the first value is the same as `FMUModelME1` but the second values indicates if the simulation should be terminated or not.

I will make a ticket to update this.
